tap "1password/tap"
tap "aws/tap"
tap "gcenx/wine"
tap "hashicorp/tap"
tap "homebrew/bundle"

brew "asdf"
brew "aws-sam-cli"
brew "awscli"
brew "cmake"
brew "colordiff"
brew "curl"
brew "direnv"
brew "gawk"
brew "ghq"
brew "git"
brew "graphviz"
brew "htop"
brew "httpie"
brew "ipcalc"
brew "jq"
brew "mas"
brew "ninja"
brew "peco"
brew "poetry"
brew "reattach-to-user-namespace"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "zsh"
brew "zsh-completions"

cask "1password"
cask "1password-cli"
cask "aquaskk"
cask "arc"
cask "caffeine"
cask "cursor"
cask "docker"
cask "godot"
cask "iterm2"
cask "microsoft-remote-desktop"
cask "onyx"
cask "raycast"
cask "steam"
cask "temurin"
cask "the-unarchiver"
cask "visual-studio-code"
cask "vnc-viewer"
cask "warp"
cask "zoom"

mas "Keynote", id: 409183694
mas "Pages", id: 409201541
mas "Numbers", id: 409203825
mas "Logic Pro", id: 634148309
mas "RunCat", id: 1429033973

vscode "vscode-icons-team.vscode-icons"
